import type { Metadata } from 'next'
import '@app/styles/globals.scss'
import { roboto } from '@/source/app/fonts'
import {HeaderUI} from "@/source/widgets/headerUI";
import {FooterUI} from "@/source/widgets/footerUI";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={`${roboto.variable}`}>
      <HeaderUI/>
        <div className="main-container">{children}</div>
      <FooterUI/>
      </body>
    </html>
  )
}
